# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# aliases
if command -v eza &> /dev/null; then
  alias ls='eza -lh --group-directories-first --icons=auto'
  alias lsa='ls -a'
  alias lt='eza --tree --level=2 --long --icons --git'
  alias lta='lt -a'
fi

alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias grep='grep --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# envs
export PATH="/home/mdray/.bun/bin:$PATH"
export EDITOR=nvim
export SUDO_EDITOR="$EDITOR"
export SYSTEMD_EDITOR="$EDITOR"

# init
if command -v mise &> /dev/null; then
  eval "$(mise activate bash)"
fi

if command -v starship &> /dev/null; then
  eval "$(starship init bash)"
fi

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
fi

if command -v fzf &> /dev/null; then
  if [[ -f /usr/share/fzf/completion.bash ]]; then
    source /usr/share/fzf/completion.bash
  fi
  if [[ -f /usr/share/fzf/key-bindings.bash ]]; then
    source /usr/share/fzf/key-bindings.bash
  fi
fi

# input
set meta-flag on
set input-meta on
set output-meta on
set convert-meta off
set completion-ignore-case on
set completion-prefix-display-length 2
set show-all-if-ambiguous on
set show-all-if-unmodified on
set mark-symlinked-directories on
set match-hidden-files on
set page-completions off
set completion-query-items 200
set visible-stats on
set skip-completed-text on
set colored-stats on

# prompt
force_color_prompt=yes
color_prompt=yes

PS1=$'\uf0a9 '
PS1=$'\[\e]0;\w\a\]$PS1'

# shell
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=32768
HISTFILESIZE='${HISTSIZE}'

if [[ ! -v BASH_COMPLETION_VERSINFO && -f /usr/share/bash-completion/bash-completion ]]; then
  source /usr/share/bash-completion/bash_completion
fi

set +h
